trunk/research/players/js/srs.player.js
trunk/research/players/srs_player/src/srs_player.as

在我们的项目中，srs_player.swf 与js,css等静态资源被部署到单独的域名下。
这触发了两个问题
1. srs.player.js 引用的是swf的相对地址，无法找到。
2. srs_player.swf 与js的交互需要允许跨域。
对于(1)，在js中SrsPlayer对象添加了set_srs_player_url()方法。
对于(2)，在as中添加了跨域许可。

为research/players/srs_player 考虑静态资源部署到单独域名的情况

---

trunk/src/kernel/srs_kernel_stream.cpp

wrong use of size in SrsStream::initialize of  srs_kernel_stream.cpp

fix bug for build failure when configure with --log-info

---

trunk/src/app/srs_app_http_hooks.cpp

Only add one line, see [diff](https://github.com/FlowerWrong/srs/commit/9ddd0054a17b4dbee76294387b91bf7342530b80#diff-74b96fe66df78acf666fd22f3d16604aR141).

Add tcUrl to on_publish http hook for issue #548

---

trunk/src/app/srs_app_thread.cpp

我详细描述一下问题
在SrsThread::stop()函数中是先loop = false, 然后再执行SrsThread::dispose()函数，
在SrsThread::thread_cycle()中退出loop，变量disposed = true，
这样的话，就有可能在执行SrsThread::dispose()之前变量disposed就赋值为true，导致SrsThread::dispose()函数直接return了
还有个问题，我就注释了一行代码，上面是issue546#546的描述，我觉得#546的出现是因为在handler->on_thread_stop()只后执行了disposed的赋值，因为对于SrsConnection来说在handler->on_thread_stop()中是删除自己的操作，也就是free当前的thread，所以任何在handler->on_thread_stop()之后的任何操作都会出错

srs reusable thread need join

---

trunk/src/app/srs_app_log.cpp

Normally if the stdout is connected to a PTY, the `stdout` buffer is flushed automatically after each `\n`.
However if I run SRS under Docker (or other container services), the `stdout` is not connected to a PTY (unless I ask it to), causing the last log line to be incomplete (showing only half).
By adding `fflush`, we could make sure each log line is completely shown, whenever the `stdout` is connected to a PTY or not.
P.S. I am working on an SRS Docker image, which allows "one-key installing" SRS on a huge cluster of servers. It is available at <https://hub.docker.com/r/m13253/srs/>, with build script available at <https://github.com/m13253/docker-srs>.

Flush the stdout buffer after logging to console

---

trunk/src/app/srs_app_statistic.cpp

HTTP API for streams is not correct. When stream stopped, API does not
remove it. 
Issue #634

FIX：When stream stopped，Stream API does not remove it。

---

trunk/src/app/srs_app_caster_flv.cpp

修复内存泄漏：
KERNEL: 在stream_caster功能模块，未释放SrsConnection连接对象
issue见：
https://github.com/ossrs/srs/issues/826

fix #826, fix memory leak in streamCasterFlv

---

trunk/src/app/srs_app_http_stream.cpp
trunk/src/app/srs_app_source.cpp
trunk/src/kernel/srs_kernel_consts.hpp

修改SRS_CONSTS_RTMP_PULSE_TMMS的定义 从500 改为500*1000，如果是500，在使用http-flv播放时单个cpu会占100%的问题

Fix the timebase bug, change from us to ms.

---

trunk/etc/init.d/srs

Hi, @winlinvip 
there are two points may need to be update:
1. In function of start, since srs is already running and failed_msg is used, maybe it's not proper to return 0.
2. this check will always success after ret=$?
thanks.

update init.d file

---

trunk/conf/full.conf
trunk/src/app/srs_app_fragment.cpp
trunk/src/app/srs_app_hls.cpp

增加生成ts切片时，在srs配置选项中增加[duration]变量可生成每个ts切片的时长，此功能在ts切片用于回看或时移可以使用，也比较实用
目前获取ts切片的时长，可以通过on_hls回调获得，测试过程，发现如果同时推流上百，上千流时，使用回调获取时不稳定，而且会影响直播服务的性能
修改代码后，可修改下面配置来通过变量获取切片时长
下面是修改后srs.conf相关配置项增加[duration]变量
```
enabled on;
hls {
enabled on;
hls_fragment 5;
hls_window 25;
hls_cleanup     off;
hls_path /nas/hls;  
hls_m3u8_file [app]/[stream].m3u8;
hls_ts_file [app]/[stream]/[2006][01][02][15]/[timestamp]_[duration].ts;
}
}
```
生成的切片文件实例:
```
-rw-r--r-- 1 root root  1.1M Mar  6 10:06 1520301978199_7420.ts
-rw-r--r-- 1 root root  434K Mar  6 10:06 1520301985520_5615.ts
-rw-r--r-- 1 root root  1.2M Mar  6 10:06 1520301991444_9737.ts
-rw-r--r-- 1 root root  935K Mar  6 10:06 1520302001017_8081.ts
-rw-r--r-- 1 root root  368K Mar  6 10:06 1520302009187_6027.ts
-rw-r--r-- 1 …
```

add: hls configuration adds [duration] variable

---

trunk/src/kernel/srs_kernel_utility.cpp

When creating TS slices, after the creation of the directory, the check state is not true, resulting in the failure of the publish stream.

fix create dir success result check

---

trunk/src/app/srs_app_server.cpp
trunk/src/app/srs_app_utility.cpp
trunk/src/kernel/srs_kernel_codec.cpp
trunk/src/kernel/srs_kernel_utility.cpp

fix security scan report issue #1172 #1173 #1174 #1175

fix security scan report issue #1172 #1173 #1174 #1175

---

trunk/src/app/srs_app_http_conn.cpp

eg: 
when request is "http://localhost/app/stream.flv?token=xxx&salt=yyy", the http callback from srs will take the param("?token=xxx&salt=yyy") in param field

fix: support transfer flv query params by callback

---

trunk/src/srt/srt_conn.cpp

update streamid decode for get more encoder such as VMIX.
If streamid is "123456", the rtmp address become rtmp://127.0.0.1/live/123456 in default publish mode.
This is for encoder such as VMIX.

update streamid decode for get more encoder such as VMIX

---

trunk/configure

* "inet addr" is not compatible with rhel/centos 7+;
* ifconfig has been replaced by ip-utils in newer distro;

Remove unused ip variable

---

trunk/src/app/srs_app_rtsp.cpp
trunk/src/app/srs_app_rtsp.hpp
trunk/src/app/srs_app_server.cpp
trunk/src/app/srs_app_server.hpp

rtsp连接断开后，释放rtsp连接时出现断言，导致程序退出：
[2020-02-17 18:00:54.353][Trace][8480][897] rtsp: ignore header User-Agent=Lavf57.56.101
srs: src/app/srs_app_st.cpp:146: virtual void SrsSTCoroutine::stop(): Assertion `!r0' failed.
Aborted
[root@iZ8vbd93czg2ytwfhy1fmnZ trunk]#

Fix disconnect RTSP connection has assertion, resulting in program exit

---

trunk/ide/srs_clion/CMakeLists.txt

原先的CMakeLists.txt 在clion无法编译通过。修改后测试推拉流正常。

更新CMakeLists.txt文件，使项目能在clion编译通过

---

trunk/conf/push.gb28181.conf
trunk/configure
trunk/src/app/srs_app_config.cpp
trunk/src/app/srs_app_config.hpp
trunk/src/app/srs_app_gb28181.cpp
trunk/src/app/srs_app_gb28181.hpp
trunk/src/app/srs_app_gb28181_sip.cpp
trunk/src/app/srs_app_gb28181_sip.hpp
trunk/src/app/srs_app_http_api.cpp
trunk/src/app/srs_app_http_api.hpp
trunk/src/app/srs_app_server.cpp
trunk/src/app/srs_app_server.hpp
trunk/src/kernel/srs_kernel_error.hpp
trunk/src/protocol/srs_sip_stack.cpp
trunk/src/protocol/srs_sip_stack.hpp

1.支持srs内部sip服务使能
2.支持只转发28181流到srs
3.接收流支持多路复用，多路复用默认启用，通过api可以选择随机端口，不使用复用端口
4.api控制
sip信令api
1. sip_invite  通知设备发流到srs
2. sip_bye     停止设备发流
3. sip_unregister  从srs内部删除注册，需重新走注册流程
4. sip_raw_data    给设备发送sip命令数据，主要用于调试sip信令用
媒体通道api
1.create_channel 创建媒体通道
2.query_channel  查询媒休通道
4.delete_channel 删除媒体通道

refactor gb28181, supporting SIP server enable, multiplex, API interface

---

trunk/src/srt/srt_handle.cpp

srt_getsockopt SRTO_MAXBW memory overflow, The epoll event error is caused. The reading event is registered incorrectly  with mac platform

SRT: fix, getsockopt SRTO_MAXBW memory overflow

---

trunk/src/app/srs_app_statistic.cpp

需要把 int64_t转化为字符串 再 赋值给 SrsStatisticStream类的成员变量id

fixbug  通过http api接口 获取 的 stream id是乱码

---

trunk/src/app/srs_app_edge.cpp
trunk/src/app/srs_app_edge.hpp

Edge: 防止ingester多次调用stop导致崩溃

---

trunk/src/app/srs_app_gb28181.cpp

incomplete_len 在大华摄像头下，大华可能会在包头填上音频的固定长度320， 而实际数据域却没有数据，导致incomplete_len被减为负值。
当incomplete_len 为负数情况下， 由于sizeof(SrsPsPacketStart）返回的是unsigned类型， 因此C++会将负数转为unsigned与sizeof(SrsPsPacketStart）做比较，导致代码进入异常分支。

incomplete_len 在大华摄像头下，可能为负值,增加兼容性判断

---

trunk/src/app/srs_app_config.cpp

bugfix: misleading error log information for transcode engine config param.

misleading error log information for transcode engine config param

---

trunk/src/app/srs_app_sctp.hpp

Report an error as follows
```
./configure --osx --sctp=on --debug=on && make
```
For details
```
src/app/srs_app_sctp.cpp:161:38: error: use of undeclared identifier 'SCTP_DEBUG_ALL'
usrsctp_sysctl_set_sctp_debug_on(SCTP_DEBUG_ALL);
```
This issue is fixed.

fix(sctp): fix build for debug or verbose.

---

README.md
trunk/research/players/js/srs.sdk.js
trunk/research/players/rtc_publisher.html
trunk/src/app/srs_app_rtc_api.cpp
trunk/src/app/srs_app_rtc_conn.cpp
trunk/src/app/srs_app_rtc_server.hpp
trunk/src/core/srs_core_version4.hpp

Use query `?codec=av1` to publish and play with AV1:
* Publish stream: [webrtc://localhost/live/livestream?codec=av1](http://localhost:8080/players/rtc_publisher.html?autostart=true&codec=av1)
* Play stream: [webrtc://localhost/live/livestream?codec=av1](http://localhost:8080/players/rtc_player.html?autostart=true&codec=av1)
First, please upgrade your Chrome to M90+:
The video codec is `Video: AV1X, 90000HZ, pt: 35`

RTC: Support av1 for Chrome M90 enabled it. 4.0.91

---

README.md
trunk/conf/full.conf
trunk/src/app/srs_app_config.cpp
trunk/src/app/srs_app_config.hpp
trunk/src/app/srs_app_hourglass.cpp
trunk/src/app/srs_app_hourglass.hpp
trunk/src/app/srs_app_hybrid.cpp
trunk/src/app/srs_app_hybrid.hpp
trunk/src/app/srs_app_listener.cpp
trunk/src/app/srs_app_rtc_codec.cpp
trunk/src/app/srs_app_rtc_codec.hpp
trunk/src/app/srs_app_rtc_conn.cpp
trunk/src/app/srs_app_rtc_server.cpp
trunk/src/app/srs_app_rtc_server.hpp
trunk/src/app/srs_app_rtc_source.cpp
trunk/src/app/srs_app_rtc_source.hpp
trunk/src/app/srs_app_rtmp_conn.cpp
trunk/src/app/srs_app_source.cpp
trunk/src/app/srs_app_source.hpp
trunk/src/core/srs_core_version4.hpp
trunk/src/kernel/srs_kernel_codec.hpp
trunk/src/kernel/srs_kernel_rtc_rtp.cpp
trunk/src/kernel/srs_kernel_rtc_rtp.hpp

This PR supports:
1. Refine audio transcoder for transcoding aac to opus.
2. Support transcode opus to aac.
3. Support transmux RTC to RTMP.
Why it's so important?
1. RTC DVR, we publish stream by WebRTC. The stream is h.264+opus,  so the audio is transcoded to aac, then SRS will DVR to FLV or MP4 file.
2. In a video room, there might be some WebRTC streams, which can be transmux to RTMPs. We can use FFmpeg to transcode and merge RTMP streams, then publish as live. That is transcode a video room to a RTMP stream.
3. Publish by WebRTC and play by RTMP, which use Chrome as a encoder for live broadcasting.
What's now and next?
1. Now this PR supports transmux WebRTC to RTMP.
2. After merged, it's able to DVR WebRTC stream.
3. In the near future, we will write some demos for video room and …

Support transmux RTC to RTMP.

---

trunk/src/app/srs_app_rtmp_conn.cpp

1. 开启GB28181功能，ipc注册之后，会生成stream name 为`34020000001320000001@34020000001320000001`的source。
2. 然后用ffmpeg推送rtmp，url为`rtmp://ip:port/live/34020000001320000001@34020000001320000001`，二者发生冲突
详见 https://github.com/ossrs/srs/issues/2364
在`SrsRtmpConn::acquire_publish`增加判断逻辑即可。

解决gb推流和rtmp推流冲突bug

---

.gitignore
trunk/conf/push.gb28181.conf
trunk/src/app/srs_app_gb28181.cpp
trunk/src/app/srs_app_gb28181.hpp

修复rtp解析错误。
删除冗余代码。
fix https://github.com/ossrs/srs/issues/2217

GB28181: fix parse rtp-tcp failed

---

trunk/src/app/srs_app_hls.cpp

fix bug: last segment of ts not trigger 'on_hls', because of 'on_unpublish' earlier than 'segment_close',
see https://github.com/ossrs/srs/issues/2068
**现象**：推流结束后，最后一个hls切片没有触发`on_hls` 
**原因**：在`SrsHlsController::on_unpublish()`这个函数里面，`on_unpublish`早于 `segment_close`，导致最后一个切片通知被**遗忘**在tasks里面。
**解决**：将`on_unpublish`置于 `segment_close`后面即可。
```
srs_error_t SrsHlsController::on_unpublish()
{
srs_error_t err = srs_success;
if ((err = muxer->on_unpublish()) != srs_success) {    
return srs_error_wrap(err, "muxer unpublish");                
}           
if ((err = muxer->flush_audio(tsmc)) != srs_success) {           
return srs_error_wrap(err, "hls: flush audio");                     
}       
if ((err = muxer->segment_close()) != srs_success) {              
return srs_error_wrap(err, "hls: …
```

fix bug: last segment of ts not trigger 'on_hls'

---

trunk/src/app/srs_app_config.cpp
trunk/src/app/srs_app_http_api.cpp

check 'vhost' validity in 'http raw dvr api', for https://github.com/ossrs/srs/issues/2015

check 'vhost' validity in 'http raw dvr api'

---

trunk/src/app/srs_app_rtmp_conn.cpp

打开rtmp转rtc，当rtmp重复推流时，第2路会影响第1路流的正常播放。

---

trunk/src/app/srs_app_rtc_codec.cpp

fix bug: update channel_layout by channels in class SrsAudioTranscoder, for ffmpeg transcode opus to aac success

---

trunk/src/app/srs_app_rtc_sdp.cpp

RTC: Trim SDP line space for pion/webrtc client.

---

trunk/src/app/srs_app_rtc_source.cpp

**现象**：使用rtc2rtmp时，开启twcc之后（默认开启），用getDisplayMedia推流，播放flv出错。关闭twcc之后，播放正常。
**原因**：
1. 开启twcc
1.1. 如果实际编码带宽低于预测带宽，会主动发送padding。
1.2. 通过抓包分析，有些packet是纯padding，也就是有效负载的payload_size为0。
由于代码的漏洞（没错，这是个bug），flv包会填充很多0x00。如下图所示。
1.3. Firefox或者ffplay面对这种空包，会提示错误，但选择忽略并继续播放。而Chrome校验严格，直接报错，也就导致了flv无法播放。
2. 关闭twcc时，不会有padding包，所以能够播放正常。
**解决**：
1. 计算出正确的payload_size即可。见代码。
> 参考文章： [WebRTC m79中的RTP padding](https://blog.csdn.net/dobe_yang/article/details/104944949)

Calculate the correct payload_size which pure padding data, in the process of rtc2rtmp, make Chrome happy

---

trunk/src/app/srs_app_rtc_conn.cpp

1. SRS回复的answer sdp里面，没有rtcp-fb nack字段。
1. Chrome默认**开启**nack，所以尽管SRS的answer没有开启NACK，也没问题。
1. Firefox默认**关闭**nack，所以SRS的answer没有开启NACK，就会有丢包导致的卡顿。
网络抖动时，由于Firefox不会发送nack，造成视频卡顿。
增加rtcp-fb nack字段，相当于手动开启firefox的nack功能，解决丢包造成的卡顿。
@see https://github.com/ossrs/srs/issues/2371

RTC: Fix NACK negotiation bug for Firefox.

---

trunk/src/app/srs_app_http_stream.cpp

> 惢畾 提问：rtmp推流，http-flv拉流时，控制台中的所有客户端ip全部是推流机器的ip，rtmp拉流时正常，请问如何解决？
fix bug for https://t.zsxq.com/EqNbUrN

fix bug: correct the client ip of http-flv player, for statistic

---

trunk/src/app/srs_app_rtc_conn.cpp

因 rebase操作，前面提交变更了tcUrl，导致以下代码失效
```
std::vector<SrsRtcTrackDescription *> video_track_descs = select_video_track_descs(stream_desc->video_track_descs_, req->tcUrl);
```
此提交更新为 param，即
```
std::vector<SrsRtcTrackDescription *> video_track_descs = select_video_track_descs(stream_desc->video_track_descs_, req->param);
```

For #2420, support simulcast for multiple streams

---

trunk/src/app/srs_app_process.cpp
trunk/src/app/srs_app_process.hpp

Fix #1695 
srs进程fork后，因为输出重定向写错误而返回，导致fork的子进程未能退出，从而导致系统资源耗尽。

Ingest: Exit if child process redirect io failed

---

trunk/src/app/srs_app_http_hooks.cpp

Add stream and param to hook call on_connect for better use

Enhancement: Add param and stream to on_connect

---

trunk/src/kernel/srs_kernel_utility.cpp
trunk/src/utest/srs_utest_kernel.cpp

fix srs_string_replace deap loop when new_str inclue old_str
bug: https://github.com/ossrs/srs/issues/2084

fix srs_string_replace deap loop when new_str inclue old_str

---

trunk/src/app/srs_app_config.cpp
trunk/src/kernel/srs_kernel_utility.cpp
trunk/src/kernel/srs_kernel_utility.hpp
trunk/src/utest/srs_utest_kernel.cpp

refine rtmp listen ip and port check

For #1920, refine rtmp listen ip and port check

---

trunk/src/protocol/srs_service_http_client.cpp

Set empty HTTP paths to '/' to avoid malformed requests

---

trunk/src/app/srs_app_rtc_source.cpp

* This can cause webrtc video PacketBuffer assemble corrupt when (nal size - 1) % 1300 == 0
* issues about webrtc caton all caused by this bug

[rtc] *Fix Fua package bug(payload size minus one).

---

trunk/src/app/srs_app_gb28181.cpp

解析ps流中 program stream map 时 es_info_length overflow es_map_length, 导致core的问题

GB28181: Check is es_info_length overflow es_map_length

---

trunk/src/app/srs_app_edge.cpp

**问题：** Edge: 最后一个拉流断开后，在3秒内再次请求相同的流，无法正常顺畅播放 https://github.com/ossrs/srs/issues/2215
**分析：** 3秒内再次请求时，state处于stopping状态
**解决：** 当处于stopping时，返回错误，给用户一个明确的提示
**TODO：** @IAmCodingCoding 给出了一个优化的方案，可以快速退出，不必等待3秒。见https://github.com/ossrs/srs/issues/2215#issuecomment-901682601 。

Refuse edge request when state is stopping

---

trunk/src/app/srs_app_rtc_source.cpp

fix #2704, no sound when play webrtc if the audio codec is G.711a or G711mu

fix #2704, no sound when play webrtc if the audio codec is G.711a or G711mu

---

trunk/src/app/srs_app_rtc_source.cpp
trunk/src/app/srs_app_rtc_source.hpp

用SR同步时间戳的时候, 因为计算偏差会导致同一个视频帧的时间戳有1/-1的差距
RTC转RTMP时, 某些情况下会把同一帧划分成两个帧, 导致视频卡顿.

Rtc2Rtmp: using rtp timestamp to distinguish different video frame

---

trunk/src/app/srs_app_rtc_source.cpp

详见gdb日志
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000617774 in SrsRtpPacket::payload (this=0x0) at src/kernel/srs_kernel_rtc_rtp.hpp:317
317	    ISrsRtpPayloader* payload() { return payload_; }
Missing separate debuginfos, use: debuginfo-install glibc-2.17-325.el7_9.x86_64 libgcc-4.8.5-44.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64
(gdb) bt
#0  0x0000000000617774 in SrsRtpPacket::payload (this=0x0) at src/kernel/srs_kernel_rtc_rtp.hpp:317
#1  0x0000000000611a2e in SrsRtmpFromRtcBridger::packet_video_rtmp (this=0x18b1310, start=0, end=17707) at src/app/srs_app_rtc_source.cpp:1632
#2  0x0000000000610b61 in SrsRtmpFromRtcBridger::packet_video (this=0x18b1310, src=0x207ef20) at src/app/srs_app_rtc_source.cpp:1452
#3  0x0000000000610446 in SrsRtmpFromRtcBridger::on_rtp …
```

fix(rtc): fix crash when pkt->payload() if pkt is nullptr

---

trunk/src/app/srs_app_rtc_codec.cpp

fix #2690, 如果发现音频包为空，则不送解码，以免提前结束了解码上下文

fix #2690, 如果发现音频包为空，则不送解码，以免提前结束了解码上下文

---

trunk/src/app/srs_app_rtc_source.cpp
trunk/src/app/srs_app_rtc_source.hpp
trunk/src/utest/srs_utest_rtc.cpp

1. Cache IDR frame's rtp timestamp instead of avsync timestamp.
2. Cache clock rate calculate by sender report.
3. Using srs_rtp_seq_distance instead of direct minus.
4. Add utest of av timestamp sync when duplicated sender report.

Fix bugs for RTC2RTMP.

---

trunk/src/app/srs_app_rtc_source.cpp

* fix memory leak when replace rtp packet in cache.

RTC: Fix memory leak when replace rtp packet in cache.

---

trunk/research/players/js/srs.page.js
trunk/research/players/js/srs.sdk.js
trunk/research/players/rtc_publisher.html
trunk/research/players/rtc_publisher_simulcast.html
trunk/research/players/srs_bwt.html
trunk/research/players/srs_chat.html
trunk/research/players/srs_gb28181.html
trunk/research/players/srs_player.html
trunk/research/players/srs_player_deprecated.html
trunk/research/players/srs_publisher.html
trunk/research/players/vlc.html
trunk/src/app/srs_app_rtc_conn.cpp
trunk/src/app/srs_app_rtc_conn.hpp
trunk/src/app/srs_app_rtc_sdp.cpp
trunk/src/app/srs_app_rtc_sdp.hpp
trunk/src/app/srs_app_rtc_source.cpp
trunk/src/app/srs_app_rtc_source.hpp
trunk/src/app/srs_app_server.cpp
trunk/src/kernel/srs_kernel_rtc_rtp.cpp
trunk/src/kernel/srs_kernel_rtc_rtp.hpp

open Simulcast推流 (`/players/rtc_publisher_simulcast.html` page)
open RTC播放器 (`/players/rtc_player.html` page)
low: webrtc://127.0.0.1/live/livestream?layer=low
mid: webrtc://127.0.0.1/live/livestream?layer=mid
high: webrtc://127.0.0.1/live/livestream?layer=high
Related Link: https://github.com/ossrs/srs/pull/2420

Support Simulcast Stream (RID Based Simulcast)

---

trunk/src/app/srs_app_rtc_conn.cpp

Fix the WebRTC **"no found valid AV1 payload type"** issue

RTC: Replace payload name AV1X with AV1 for WebRTC. (#2760)

---

trunk/src/app/srs_app_rtc_source.cpp

when video_track call on_rtp function, duplicate assignment packet's frame_type.
```
pkt->frame_type = SrsFrameTypeVideo;
```

RTC: Eliminate duplicate assignment for video packet frame type 

---

trunk/src/app/srs_app_http_static.cpp
trunk/src/app/srs_app_http_static.hpp
trunk/src/protocol/srs_http_stack.cpp
trunk/src/protocol/srs_http_stack.hpp
trunk/src/protocol/srs_service_http_conn.cpp

背景：#2780 #2781 ，http服务分发超过2GB大文件时(如flv、mp4)，会出现连接超时或者overflow日志
原因：超过2GB后，`int`类型无法完整表示文件大小

HTTP: Fix mp4/flv file size exceed 2GB download error

---

.github/workflows/test.yml
trunk/Dockerfile.builds

Enable CentOS 6.0 CI
Support baseline build and utest.

CI: Support build and test for CentOS 6.0

---

trunk/src/srt/srt_to_rtmp.cpp

eliminate unused `#include < list >` and duplicate `#include <sstream>`, because srs_app_config.hpp have introduced.

SRT: Eliminate duplicate header file.(#2786)

---

trunk/src/app/srs_app_rtc_conn.cpp
trunk/src/app/srs_app_rtc_source.cpp
trunk/src/app/srs_app_rtc_source.hpp
trunk/src/app/srs_app_source.cpp

Rule: One simulcast(low,mid,high) stream to Multiple rtmp streams ( rtmp://xxx_{low,mid,high} )
Related Link: #2420, #2659

Support Simulcast To RTMP

---

trunk/src/app/srs_app_rtc_api.cpp

After the RTMP publishing is disconnected, then I publish RTC stream and the RTC playing will be rejected.Likely:
My config as follows,
```
rtc {
rtmp_to_rtc off;
rtc_to_rtmp off;
}
}
```
Firstly, publish rtmp stream, then disconnect.
`ffmpeg -re -i 264_aac.flv -c copy -f flv rtmp://127.0.0.1/live/livestream`
Secondly, publish rtc stream.
`./objs/srs_bench -pr webrtc://localhost/live/livestream -sa avatar.ogg -sv avatar.h264 -fps 25`
Thirdly, play is rejected.
`./objs/srs_bench -sr webrtc://localhost/live/livestream`

RTC: fix play rtc judge for rtmp inactive.(#2863)

---

trunk/src/app/srs_app_rtc_conn.cpp

When I publish rtmp firstly and then publish rtc, both streams can be published. I hope there was only one stream. My config as follows,
```
rtc {
rtmp_to_rtc off;
rtc_to_rtmp off;
}
}
```

RTC: Fix both rtmp and rtc streams can be published at the same time.

---

trunk/src/app/srs_app_rtc_source.cpp
trunk/src/app/srs_app_rtc_source.hpp
trunk/src/app/srs_app_source.cpp
trunk/src/app/srs_app_source.hpp

LiveSource's fetch function should be extended Parameters, because it update the request.

LiveSource: Refine fetch for external exposed interface.

---

trunk/src/app/srs_app_rtc_api.cpp
trunk/src/app/srs_app_rtc_source.hpp

```
rtc {
rtmp_to_rtc off;
rtc_to_rtmp off;
}
}
```
>Step1: Rtmp Publish: `ffmpeg -re -i 264_aac.flv -c copy -f flv rtmp://127.0.0.1/live/livestream`
Step2: Rtmp stream can play: `ffplay rtmp://localhost/live/livestream`
Step3: Rtc stream can't play(**reject tips**): `./objs/srs_bench -sr webrtc://localhost/live/livestream`
>Step1: RTC Publish: `./objs/srs_bench -pr webrtc://localhost/live/livestream -sa avatar.ogg -sv avatar.h264 -fps 25`
Step2: Rtmp stream can't play: `ffplay rtmp://localhost/live/livestream`
Step3: Rtc stream  can play: `./objs/srs_bench -sr webrtc://localhost/live/livestream`
```
rtc {
rtmp_to_rtc off;
rtc_to_rtmp on;
}
}
```
>Step1: Rtmp Publish: `ffmpeg -re -i 264_aac.flv -c copy -f …

RTC: fix play rtc judge for config rtc2rtmp on.(#2863)

---

trunk/src/kernel/srs_kernel_utility.cpp
trunk/src/protocol/srs_service_st.cpp

bugfix: getaddrinfo return cannot freed by delete

bugfix: SrsAutoFree addrinfo

---

trunk/src/protocol/srs_service_http_conn.cpp
trunk/src/utest/srs_utest_http.cpp

场景：开启HTTP HOOK
配置文件：
```
rtc_server {
enabled on;
listen 8000; # UDP port
candidate $CANDIDATE;
}
rtc {
rtmp_to_rtc on;
rtc_to_rtmp off;
}
http_remux {
mount       [vhost]/[app]/[stream].flv;
}
http_hooks {
enabled         on;
on_play         http://192.168.1.10:8888/;
}
}
```
重现步骤：
使用@mingyang0921 提供的代码搭建一个http server，即可重现。链接在此： https://github.com/ossrs/srs/pull/2851#issuecomment-1006280683
原因分析：
http response header最后一个字段的value为空，如下示例里面的`Server`：
```
Date: Fri, 31 Dec 2021 08:47:59 GMT\r\nServer: \r\n\r\n{\"code\": 0, \"data\": \"\"}
```
就会导致找不到body，以至于最终超时，错误日志如下：
```
[2022-01-23 15:40:26.982][Warn][41098][78k9o875][62] RTC error code=1011 : RTC: http_hooks_on_play : on_play http://192.168.1.10:8888/ : http: on_play failed, …
```

Fix bug when the value of http header is empty

---

trunk/src/srt/srt_handle.cpp
trunk/src/srt/srt_to_rtmp.cpp
trunk/src/srt/srt_to_rtmp.hpp
trunk/src/srt/ts_demux.cpp
trunk/src/srt/ts_demux.hpp

pass rtmp errors to srt, refer #2897

SRT: Close connection if RTMP failed.

---

trunk/conf/forward.backend.conf
trunk/conf/forward.master.conf
trunk/conf/full.conf
trunk/research/api-server/server.py
trunk/src/app/srs_app_config.cpp
trunk/src/app/srs_app_config.hpp
trunk/src/app/srs_app_forward.cpp
trunk/src/app/srs_app_http_hooks.cpp
trunk/src/app/srs_app_http_hooks.hpp
trunk/src/app/srs_app_source.cpp
trunk/src/app/srs_app_source.hpp
trunk/src/utest/srs_utest_config.cpp

You can specify livestream  forward the full rtmp address to other server, for example:
```
forward {
enabled on;
destination 127.0.0.1:1936 127.0.0.1:1937;
backend http://127.0.0.1:8085/api/v1/forward;
}
```
forward url has domain and port
```
rtmp://ossrs.net/live/livestream?forward=aliyuncdn.com:1936&token=xxxxxx
```
forward url is full rtmp address
```
rtmp://ossrs.net/live/livestream?token=xxxxxx&forward=rtmp://cdn.com/myapp/mystream
```
```
class RESTForward(object):
def __init__(self):
self.__forwards = []
self.__forwards.append({
"vhost":"ossrs.net",
"app":"live",
"stream":"livestream",
"url":"push.ossrs.com",
})
self.__forwards.append({
"app":"live",
"stream":"livestream",
"url":"rtmp://push.ossrs.com/test/teststream?auth_token=123456",
})
```

Forward: support config full rtmp url forward to other server

---

trunk/src/app/srs_app_server.cpp

when tcp connection exceed max_connection, that connection will leak because of not closing the fd
when a incoming tcp connection exceed max_connection, it will lead to fd leaking, if too many leaking happened, then http server may not respond, because of "too many open files”
same to the summary

fix fd leak

---

trunk/3rdparty/signaling/www/demos/index.html
trunk/3rdparty/signaling/www/demos/js/srs.sdk.js
trunk/3rdparty/signaling/www/demos/js/srs.sig.js
trunk/research/console/js/srs.console.js
trunk/research/console/js/winlin.utility.js
trunk/research/players/js/srs.page.js
trunk/research/players/js/srs.sdk.js
trunk/research/players/js/winlin.utility.js
trunk/research/players/srs_gb28181.html
trunk/research/players/srs_publisher.html
trunk/research/players/srs_publisher_flash.html

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) or [String.prototype.substring()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring) which work similarily but aren't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

Replace deprecated String.prototype.substr()

---

trunk/auto/depends.sh

the cmake option is ENABLE_APPS, so we should use --disable-apps or --enable-apps=0. this fixes the typo. close #2936

SRT: Fix typo in libsrt build options

---

trunk/src/app/srs_app_config.cpp
trunk/src/kernel/srs_kernel_error.cpp

Fix parse_file function did not handle err
配置文件 live.conf
```
listen              1935;
max_connections     1000;
srs_log_tank        console;
daemon              off;
http_api {
enabled         on;
listen          1985;
}
http_server {
enabled         on;
listen          8080;
dir             ./objs/nginx/html;
}
hls {
enabled         on;
}
http_remux {
mount       [vhost]/[app]/[stream].flv;
}
#} ----------------------------假定此花括号缺失
```
运行加载配置
```
./objs/srs -c ./conf/live.conf
```
运行并不会报错，提示配置文件异常。

Fix parse_file function did not handle err

---

trunk/3rdparty/libsrtp-2-fit/config.guess
trunk/3rdparty/patches/srtp/config.guess-02.patch
trunk/3rdparty/st-srs/README.md
trunk/3rdparty/st-srs/md.h
trunk/3rdparty/st-srs/md_linux.S
trunk/auto/depends.sh
trunk/src/app/srs_app_rtmp_conn.cpp
trunk/src/core/srs_core.hpp

Signed-off-by: Steven Liu <lq@chinaffmpeg.org>

Support riscv, starfive CPU.

---

trunk/src/main/srs_main_server.cpp

when srs start up, format macro features.

Main: remove extra space and refine code.

---

trunk/src/app/srs_app_rtc_conn.cpp

When the backup H.264 payload type is selected, the track desc type is not set.

WebRTC: Fix missing type in track desc when backup H.264 payload type is chosen.

---

trunk/conf/full.conf
trunk/conf/rtmp.kickoff.conf
trunk/doc/CHANGELOG.md
trunk/doc/Features.md
trunk/src/app/srs_app_config.cpp
trunk/src/app/srs_app_config.hpp
trunk/src/app/srs_app_gb28181.cpp
trunk/src/app/srs_app_rtmp_conn.cpp
trunk/src/app/srs_app_source.cpp
trunk/src/app/srs_app_source.hpp
trunk/src/core/srs_core_version5.hpp
trunk/src/core/srs_core_version6.hpp
trunk/src/kernel/srs_kernel_error.hpp
trunk/src/utest/srs_utest_config.cpp

For some use scenario, the publisher is invited when player want to view the stream:
1. Publisher connect to system, but does not publish any stream to SRS yet.
2. Player connect to system and start to request the stream.
3. System notifies publisher to publish stream to SRS.
4. Player play the stream from SRS.
Please notice that `system` means your business system, not SRS.
This is what we called `on-demand-live-streaming`, so when the last player stop to view the stream, what happends?
1. System needs to notify publisher to stop publish.
2. Or, SRS disconnect the publisher when idle(the last player stops playing).
This PR is for the solution 2, so that the cleanup is very simple, your system does not need to notify publisher to stop publish, because SRS has already disconnected the …

Kickoff publisher when stream is idle, which means no players. v6.0.31, v5.0.144
