trunk/src/app/srs_app_rtmp_conn.cpp

fix srs_app_rtmp_conn.cpp publish_normal_timeout 配置读取错误

2.0release bugfix publish_normal_timeout 配置读取错误

---

trunk/src/app/srs_app_http_api.cpp

Clients Api support start and count parameters!

Clients Api support start and count

---

trunk/3rdparty/patches/6.ffmpeg.speex.patch
trunk/3rdparty/readme.txt
trunk/auto/build_ffmpeg.sh
trunk/auto/depends.sh

Replace FFmpeg version from 2.1.1 to 3.2.4
Cause:
The old FFMpeg transcode audio from G711 Audio to AAC, it would met memory corruption.

Replace ffmpeg version from 2.1.1 to 3.2.4

---

trunk/src/app/srs_app_source.cpp

Free the message twice.

---

trunk/src/protocol/srs_http_stack.cpp

Comment port=0 and verify port in initialize function, tested

Fix #744 http callback set a wrong default port

---

trunk/3rdparty/readme.txt
trunk/auto/depends.sh
trunk/configure
trunk/ide/srs_xcode/srs_xcode.xcodeproj/project.pbxproj
trunk/research/librtmp/Makefile
trunk/src/kernel/srs_kernel_error.hpp
trunk/src/protocol/srs_rtmp_handshake.cpp

Due to API breakchange, add a wrapper for backward compatibility

Replace openssl from l-1.0.1f to 1.10e

---

trunk/research/librtmp/srs_bandwidth_check.c
trunk/src/libs/srs_librtmp.cpp
trunk/src/protocol/srs_protocol_utility.cpp
trunk/src/protocol/srs_protocol_utility.hpp

add param for generating tc url and add play stream to make bandwidth checking success

fix bug，修复srs_bandwidth_check工具不能够正常工作的问题

---

trunk/src/app/srs_app_hls.cpp
trunk/src/app/srs_app_mpegts_udp.cpp
trunk/src/app/srs_app_rtmp_conn.cpp
trunk/src/app/srs_app_server.cpp
trunk/src/app/srs_app_st.cpp
trunk/src/kernel/srs_kernel_codec.cpp
trunk/src/protocol/srs_protocol_utility.cpp

srs_info use not available variable.
Variable has been removed or changed.
FIX #812

FIX #812 srs_info use not available variable

---

trunk/src/app/srs_app_mpegts_udp.cpp
trunk/src/app/srs_app_server.cpp

fixed compile error when add --log-info

fixed compile error when add --log-info

---

trunk/src/app/srs_app_http_stream.cpp

fix st_usleep param from us to ms.

fix st_usleep param from us to ms.

---

trunk/src/kernel/srs_kernel_utility.cpp
trunk/src/kernel/srs_kernel_utility.hpp
trunk/src/protocol/srs_rtmp_utility.cpp
trunk/src/utest/srs_utest_kernel.cpp
trunk/src/utest/srs_utest_protocol.cpp

I added ignoring default instance (\_definst\_) at the end of app in RTMP-URL
Issue #1235

#1235 add ignoring _definst_ at the end of app

---

trunk/conf/srt.conf
trunk/src/app/srs_app_config.cpp
trunk/src/app/srs_app_config.hpp
trunk/src/srt/srt_handle.cpp
trunk/src/srt/srt_to_rtmp.cpp
trunk/src/srt/srt_to_rtmp.hpp
trunk/src/srt/ts_demux.cpp

1,solve audio timestamp bugs;
2,solve video dts increase bugs

solve audio timestamp bugs and video dts/pts bugs

---

trunk/src/app/srs_app_config.cpp
trunk/src/app/srs_app_config.hpp
trunk/src/srt/srt_handle.cpp
trunk/src/srt/srt_to_rtmp.cpp
trunk/src/srt/ts_demux.cpp

add h264 sei filter configure in srt2rtmp

add h264 sei filter configure

---

trunk/src/app/srs_app_gb28181.cpp
trunk/src/app/srs_app_gb28181.hpp
trunk/src/app/srs_app_gb28181_jitbuffer.cpp
trunk/src/app/srs_app_gb28181_jitbuffer.hpp
trunk/src/kernel/srs_kernel_error.hpp

1.支持ps缓冲支持动态分配，解决大码率时有可能崩的问题
2.优化jitbuffer适应大华的封装方式
3.支持g711音频格式
4.摄像机各种音视频格式检测
5.ps to h264 framesize < 0 检查

Fix GB28181 bug.

---

trunk/ide/srs_clion/CMakeLists.txt

fix: update CMakeLists.txt for rtc

---

trunk/src/app/srs_app_statistic.cpp

fix bug: memory leak in SrsStatisticClient

fix bug: memory leak in SrsStatisticClient

---

trunk/3rdparty/ffmpeg-4-fit/libavcodec/crystalhd.c

ffmpeg-4-fit/libavcodec/crystalhd.c was missing that cause compiling failed in Ubuntu 18.04/20.4.

Add missing ffmpeg-4-fit/libavcodec/crystalhd.c from ffmpeg 4.2, #2271

---

.run/srs-ingest.run.xml
trunk/3rdparty/srs-bench/srs/rtc_test.go
trunk/3rdparty/srs-bench/srs/util.go
trunk/conf/clion-ingest.conf
trunk/src/app/srs_app_rtc_conn.cpp

1. Refine API to change defaule decodes.
2. Add test for publish SDP nack.
3. Add test for play SDP nack.

For #2371: Add regression test for SDP nack

---

trunk/conf/full.conf
trunk/src/app/srs_app_http_hooks.cpp

STAT: Add server_id into http_hooks

---

trunk/src/srt/srt_handle.cpp
trunk/src/srt/srt_to_rtmp.cpp

fix url_sz memory out of bounds
fix srt play map error

SRT: fix srt stream play map error

---

trunk/src/srt/ts_demux.cpp
trunk/src/srt/ts_demux.hpp

Add member of adaptation_field and fix pos not add after memcpy.

---

trunk/src/app/srs_app_http_stream.cpp

LAS: fix build error

---

trunk/conf/push.gb28181.conf
trunk/conf/push.gb28181.tcp.conf
trunk/src/app/srs_app_config.cpp
trunk/src/app/srs_app_config.hpp
trunk/src/app/srs_app_gb28181.cpp
trunk/src/app/srs_app_gb28181.hpp

gb ps rtp jitterbuffer去掉配置开关,默认就开,相关代码的删除, issues问题发现有些是没有开启jittbuer引用,没有jit 白的代码也没有什么用了

GB28181: Always enable jitter for RTP.

---

trunk/src/app/srs_app_bandwidth.cpp

Fix issue #2519
fix kbps bandwidth calculate bug

API: Fix bandwidth kbps caculate bug

---

trunk/src/app/srs_app_rtc_api.cpp

RTC: Remove no need code when check sdp.

---

trunk/packaging/redhat/srs.init

RPM: Use user no-body to start SRS

---

trunk/src/app/srs_app_dvr.cpp
trunk/src/app/srs_app_dvr.hpp
trunk/src/app/srs_app_source.cpp

see https://github.com/ossrs/srs/issues/1613#issuecomment-960623359

DVR: copy req from publish

---

trunk/src/app/srs_app_source.cpp

LAS : fix build error

---

trunk/src/app/srs_app_server.cpp

Fix typo(HTTP-Server -> HTTPS-Server)

---

trunk/src/core/srs_core.hpp

modify a word.
Just tow words.
user -> use

Fix typo for comments in srs_core.hpp

---

trunk/src/srt/srt_to_rtmp.cpp

Replace ip and port by using consts macro.

SRT: concat rtmp url by consts macro

---

trunk/src/app/srs_app_source.cpp

bugfix:SrsMetaCache memleak

---

trunk/src/srt/srt_conn.cpp
trunk/src/srt/srt_conn.hpp
trunk/src/srt/srt_handle.cpp

Please describe the summary for this PR.
Add more details about this PR.

SRT: Reduce the SRT bug by limit the max times for retry.

---

trunk/src/app/srs_app_rtmp_conn.cpp
trunk/src/protocol/srs_protocol_utility.cpp
trunk/src/protocol/srs_protocol_utility.hpp
trunk/src/utest/srs_utest_rtmp.cpp

Support publish with Server without StreamKey using OBS

RTMP: Support publish with Server without StreamKey using OBS.(#3018)
